
print("")
print("#########################################")
print("######## WELCOME TO DUNGEON RUN #########")
print("#########################################")
print("")
print(" Please choose one of the following alternatives")
print ("")
print ("[1]<---- Create a new hero")
print ("")
print ("[2]<---- Choose an existing hero")
print ("")
print ("[0]<---- Exit the game")
opt1 = int(input("Enter your option   :"))
